# This is a basic workflow to help you get started with Actions

name: Swap Staging to Prod

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  swap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Azure CLI
      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds:  ${{ secrets.AZURE_CREDENTIALS }}
          # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login

      # Runs a single command using the runners shell
      - name: Poll POI Service
        id: POI_Polling
        run: |
          timeout 30s bash .github/polling.sh https://openhacklucalidevopspoi-staging.azurewebsites.net/api/healthcheck/poi 2>/dev/null | grep -q "| 200" 
          echo "::set-output name=result::$?"
        shell: bash {0}

      # Runs a set of commands using the runners shell
      - name: Polling result
        run: |
          echo ${{steps.POI_Polling.outputs.result}}
