name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - 'apis/poi/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apis/poi/**'
    
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

defaults:
  run:
    working-directory: ./apis/poi

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Trigger Push to ACR and deploy
      if: ${{ github.event_name == 'push' && success() }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Push to ACR and deploy
        token: ${{ secrets.PAT_GITHUB_TOKEN }}      
    - name: Issue on faild build
      id: create-issue
      if: ${{ failure() }}    
      uses: JasonEtco/create-an-issue@v2.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
      with:
        filename: .github/BUILD_ISSUE_TEMPLATE.md   
      
      
